### ISSUE TITLE
No equalization on YouTube for certain videos UNTIL I follow certain actions

### ISSUE THREAD

**Issue by Melonadev** [lunu-bounir/audio-equalizer#10]
Strangely, this issue only occurs for certain videos like these ones as examples:
https://www.youtube.com/watch?v=esjELnfFoLU
https://www.youtube.com/watch?v=WwwHQOI7hJ4
https://www.youtube.com/watch?v=UbYwbY4uCv4
https://www.youtube.com/watch?v=nXa2sKxkJbs
https://www.youtube.com/watch?v=EqzghgtJ1Is

Enter a YouTube video, and occasionally the extension would look like this:
![image](https://user-images.githubusercontent.com/66422959/103265164-e862e380-49e7-11eb-9dd5-bcd957673a2f.png)

When I hover my cursor on it, it says:
**audio source is cross-origin and equalization is not possible, badge value D
Has access to this site**
![image](https://user-images.githubusercontent.com/66422959/103268070-d2f0b800-49ed-11eb-9405-001a88098084.png)

And as expected, equalization doesn't work on the video, _until I make any of these actions:_
**1. Pause and play the video (both mouse and keyboard shortcuts work).
2. Click/skip/rewind to any point in the video (both mouse and keyboard shortcuts work).**

But when I reload the video, the issue occurs again, and I have to repeat any of the actions listed above.

**Comment by lunu-bounir** [comment]
Thanks for the report. Should be fixed by 0.1.3 release.
