### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by Kuroky-ua** [lunu-bounir/audio-equalizer#18]
good time of day. V3 application does not work with music?

**Comment by lunu-bounir** [comment]
On what website?

**Comment by lunu-bounir** [comment]
What is your browser?

**Comment by Kuroky-ua** [comment]
website https://open.spotify.com,  https://deezer.com Chrome browser version  107.0.5304.87.

**Comment by Kuroky-ua** [comment]
operating system macOS

**Comment by lunu-bounir** [comment]
Thanks! It will be fixed by the next release
https://github.com/lunu-bounir/audio-equalizer/commit/505c42a082b9f1eb29822c5afe9a2b468df22667
